import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",
  secondary: "0F5D2A",
  text: "1E293B",
  light: "F1F5F9",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
};

export const generatePpt = async (data) => {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_16x9";
  ppt.author = "MultiplexAI";
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.company = "MultiplexAI";
  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };

  addCover(ppt, data);
  if (Array.isArray(data?.slides)) {
    data.slides.forEach((s, i) => {
      addContentSlide(
        ppt,
        s.title || s.heading,
        s.points,
        i + 1,
        data.slides.length,
      );
    });
  }
  addThankYou(ppt);

  return ppt;
};

const addCover = (ppt, data) => {
  const slide = ppt.addSlide();
  slide.background = {
    color: COLORS.primary,
  };

  slide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 0,
    w: "100%",
    h: 0.2,
    fill: { color: "655FFA" },
    line: { color: "655FFA" },
  });
  slide.addText(data.title || "", {
    x: 0.8,
    y: 1.8,
    w: 10,
    h: 0.6,
    align: "center",
    color: COLORS.white,
    bold: true,
    fontSize: 28,
  });
  slide.addText(data.subtitle || "", {
    x: 1,
    y: 2.8,
    w: 11.0,
    h: 0.4,
    align: "center",
    color: "DEFDFE",
    fontSize: 20,
  });
  slide.addText("Generated by Multiplex AI", {
    x: 0,
    y: 6.5,
    w: 11.0,
    h: 0.2,
    align: "center",
    color: "BFEDFE",
    fontSize: 10,
  });
};

const addContentSlide = (ppt, title, points, pageNumber, total) => {
  const slide = ppt.addSlide();
  slide.background = {
    color: COLORS.white,
  };
  slide.addText(title || "", {
    x: 0.6,
    y: 0.35,
    w: 10,
    h: 0.5,
    color: COLORS.primary,
    bold: true,
    fontSize: 26,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 0.6,
    y: 0.8,
    w: 12,
    h: 0,
    line: {
      color: COLORS.border,
      width: 1.3,
    },
  });

  const pointsPerSlide = (points || []).slice(0, 6);
  pointsPerSlide.forEach((point, index) => {
    const y = 1.2 + index * 0.7;

    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.6,
      y,
      w: 9,
      h: 0.5,
      fill: {
        color: index % 2 ? "F888EB" : "EFF6AD",
      },
      line: {
        color: COLORS.border,
      },
      radius: 0.06,
    });
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.95,
      y: y + 0.18,
      w: 0.12,
      h: 0.12,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });
    slide.addText(point, {
      x: 1.2,
      y: y + 0.08,
      w: 11,
      h: 0.35,
      color: COLORS.text,
      fit: "shrink",
      fontSize: 16,
    });
  });

  slide.addText(`\({pageNumber}/\){total}`, {
    x: 12.2,
    y: 6.9,
    w: 0.8,
    h: 0.2,
    align: "right",
    color: COLORS.muted,
    fontSize: 10,
  });
  slide.addText(`Multiplex AI`, {
    x: 0.6,
    y: 6.9,
    w: 2,
    h: 0.2,
    color: COLORS.muted,
    fontSize: 10,
  });
};

const addThankYou = (ppt) => {
  const slide = ppt.addSlide();
  slide.background = {
    color: COLORS.secondary,
  };
  slide.addText(`Thank You`, {
    x: 0,
    y: 1.9,
    w: 10,
    h: 0.8,
    align: "center",
    color: COLORS.white,
    fontSize: 34,
    bold: true,
  });
  slide.addText(`Generated By MultiplexAI`, {
    x: 0,
    y: 6.9,
    w: 12.8,
    h: 0.4,
    align: "center",
    color: COLORS.white,
    fontSize: 10,
  });
};
